# Generated by Django 5.2.8 on 2025-11-27 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_codigo', models.CharField(max_length=20)),
                ('parceiro_codigo', models.CharField(max_length=20)),
                ('natureza_codigo', models.CharField(max_length=20)),
                ('projeto_codigo', models.CharField(max_length=20)),
                ('tipo_negociacao_codigo', models.CharField(max_length=20)),
                ('tipo_operacao_codigo', models.CharField(max_length=20)),
                ('moeda_codigo', models.CharField(max_length=10)),
                ('obs_interna', models.TextField()),
                ('empresa', models.CharField(max_length=255)),
                ('parceiro', models.CharField(max_length=255)),
                ('natureza', models.CharField(max_length=255)),
                ('projeto', models.CharField(max_length=255)),
                ('tipo_negociacao', models.CharField(max_length=255)),
                ('data_emissao', models.DateField()),
                ('pagamento_urgente', models.BooleanField(default=False)),
                ('justificativa_urgencia', models.TextField(blank=True)),
                ('produto_novo', models.BooleanField(default=False)),
                ('nome_produto_novo', models.CharField(blank=True, max_length=255)),
                ('parceiro_novo', models.BooleanField(default=False)),
                ('nome_parceiro_novo', models.CharField(blank=True, max_length=255)),
                ('cnpj_parceiro_novo', models.CharField(blank=True, max_length=20)),
                ('pagamento_parcelado', models.BooleanField(default=False)),
                ('descricao_parcelas', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado'), ('Concluído', 'Concluído')], default='Aberto', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='notas_fiscais/')),
                ('boleto', models.FileField(blank=True, null=True, upload_to='boletos/')),
                ('chamado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.chamado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('codvol', models.CharField(max_length=10)),
                ('quantidade', models.FloatField()),
                ('vlrunit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('centro_resultado_codigo', models.CharField(max_length=20)),
                ('produto_novo_flag', models.BooleanField(default=False)),
                ('natureza_item_codigo', models.CharField(max_length=20)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='chamados.chamado')),
            ],
        ),
    ]
