# Generated by Django 5.2.8 on 2025-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchamado',
            name='observacao_item',
            field=models.TextField(blank=True),
        ),
    ]
